spring.application.name=nvt-project

# --- PostgreSQL Config ---
spring.datasource.url=jdbc:postgresql://localhost:5433/nvt_db
spring.datasource.username=nvt_user
spring.datasource.password=nvt_pass

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true

spring.sql.init.separator=@@
spring.sql.init.schema-locations=classpath:schema.sql,classpath:schema-postgres.sql
spring.sql.init.data-locations=classpath:data.sql

# --- InfluxDB Config (v2) ---
influxdb.url=http://localhost:8086
influxdb.token=rnyi-_h_ibyWJ5Fw6drxzofQnNgWEBwWLhUib7M2oB6RceqNKbqLUwMTI9ccdMB_uOJahoaIAGgpJenVL47iPw==
influxdb.org=nvt_org
influxdb.bucket=nvt_bucket

# --- RabbitMQ Config ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=nvt_user
spring.rabbitmq.password=nvt_password

# --- Redis Config ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=nvt_redis_pass
spring.cache.type=redis

# --- JWT Config ---
jwt.secret=your-super-secret-jwt-key-minimum-256-bits-long-change-in-production
jwt.expiration=86400000

# --- Java Mail Sender Config ---
spring.mail.host=smtp.gmail.com
spring.mail.username=diirrektorr@gmail.com
spring.mail.port=587
# ADD MAIL PASSWORD DO NOT PUSH IT TO GITLAB !!
spring.mail.password=nldssacgibstvnwt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.servlet.multipart.max-file-size=12MB
spring.servlet.multipart.max-request-size=12MB

file.storage.location=uploads
file.storage.public-base-url=http://localhost:8080/static
file.storage.default-user-image=/defaults/person-avatar.webp
file.storage.default-product-image=/defaults/product.jpg

# --- Actuator (Health Checks) ---
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Nominatim base URL
geocoding.nominatim.base-url=https://nominatim.openstreetmap.org

springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.static-path-pattern=/**
